const { Book } = require('../models');

const bookdata = [
  {
    title: 'Harry Potter and the Sorcerer\'s Stone',
    author: 'J.K. Rowling',
    publisher: 'Scholastic',
    description: 'On Harry\'s eleventh birthday, an enormous wizard named Hagrid appears and explains to Harry that he is a wizard, too. Harry\'s parents, Lily and James, were wizards who sacrificed themselves to save him from a supremely evil wizard named Voldemort.',
    isbn: '1338878921',
    genre: 'Fantasy',
    series: 'Harry Potter',
    price: '7.99',
    quantity: '25',
    condition_new: true,
    image: "hp_stone.jpg",
  },
  {
    title: 'Harry Potter and the Chamber of Secrets',
    author: 'J.K. Rowling',
    publisher: 'Scholastic',
    description: 'Harry is in his second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school\'s corridors warn that the "Chamber of Secrets" has been opened and that the "heir of Slytherin" would kill all pupils who do not come from all-magical families.',
    isbn: '0747538492',
    genre: 'Fantasy',
    series: 'Harry Potter',
    price: '7.99',
    quantity: '18',
    condition_new: true,
    image: "hp_chamber.jpg",
  },
  {
    title: 'Harry Potter and the Prisoner of Azkaban',
    author: 'J.K. Rowling',
    publisher: 'Scholastic',
    description: 'Harry is in his third year at Hogwarts School of Witchcraft and Wizardry. Along with friends Ronald Weasley and Hermione Granger, Harry investigates Sirius Black, an escaped prisoner from Azkaban, the wizard prison, believed to be one of Lord Voldemort\'s old allies.',
    isbn: '0747542155',
    genre: 'Fantasy',
    series: 'Harry Potter',
    price: '7.99',
    quantity: '32',
    condition_new: true,
    image: "hp_pris.jpg",
  },
  {
    title: 'Harry Potter and the Goblet of Fire',
    author: 'J.K. Rowling',
    publisher: 'Scholastic',
    description: 'Harry is in his fourth year at Hogwarts School of Witchcraft and Wizardry, and the mystery surrounding the entry of Harry\'s name into the Triwizard Tournament, in which he is forced to compete.',
    isbn: '074754624X',
    genre: 'Fantasy',
    series: 'Harry Potter',
    price: '7.99',
    quantity: '28',
    condition_new: true
  },
  {
    title: 'Harry Potter and the Order of the Phoenix',
    author: 'J.K. Rowling',
    publisher: 'Scholastic',
    description: 'Harry struggles through his fifth year at Hogwarts School of Witchcraft and Wizardry, including the surreptitious return of the antagonist Lord Voldemort, O.W.L.exams, and an obstructive Ministry of Magic.',
    isbn: '0747551006',
    genre: 'Fantasy',
    series: 'Harry Potter',
    price: '7.99',
    quantity: '11',
    condition_new: true
  },
  {
    title: 'Recursion',
    author: 'Blake Crouch',
    publisher: 'Random House',
    description: 'Reality is broken. At first, it looks like a disease.An epidemic that spreads through no known means, driving its victims mad with memories of a life they never lived.But the force that\'s sweeping the world is no pathogen.It\'s just the first shock wave, unleashed by a stunning discovery—and what\'s in jeopardy is not our minds but the very fabric of time itself.',
    isbn: '1524759791',
    genre: 'Science Fiction',
    series: NULL,
    price: '11.99',
    quantity: '12',
    condition_new: true
  },
  {
    title: 'The House at the End of the World',
    author: 'Dean Koontz',
    publisher: 'Thomas & Mercer',
    description: 'In retreat from a devastating loss and crushing injustice, Katie lives alone in a fortresslike stone house on Jacob\'s Ladder island. Once a rising star in the art world, she finds refuge in her painting.',
    isbn: '1662508077',
    genre: 'Science Fiction',
    series: NULL,
    price: '12.00',
    quantity: '19',
    condition_new: true
  },
  {
    title: 'The Breakthrough Effect',
    author: 'Douglas E. Richards',
    publisher: 'Independently Published',
    description: 'Oliver Scott is the reclusive genius behind countless world-changing breakthroughs. But how does he innovate at such a furious pace? And while most hail him as a savior, what if he\'s actually the most dangerous tyrant humanity has ever seen? A man who will stop at nothing to gain absolute power.',
    isbn: '979-8859904433',
    genre: 'Science Fiction',
    series: NULL,
    price: '18.00',
    quantity: '17',
    condition_new: true
  },
  {
    title: 'Lost In Time',
    author: 'A G Riddle',
    publisher: 'Head of Zeus',
    description: 'One morning, Dr. Sam Anderson wakes up to find that the woman he loves has been murdered. For Sam, the horror is only beginning. He and his daughter are accused of the crime. The evidence is ironclad. They will be convicted. And so, to ensure his daughter goes free, Sam does what he must: he confesses. But in the future, murderers aren\'t sent to prison.',
    isbn: '1804541788',
    genre: 'Science Fiction',
    series: NULL,
    price: '17.00',
    quantity: '27',
    condition_new: true
  },
  {
    title: 'Foundation',
    author: 'Isaac Asimov',
    publisher: 'Del Rey',
    description: 'For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. But only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future—to a dark age of ignorance, barbarism, and warfare that will last thirty thousand years.',
    isbn: '0593497481',
    genre: 'Science Fiction',
    series: 'Foundation',
    price: '11.00',
    quantity: '37',
    condition_new: true
  },
  {
    title: 'Hidden Pictures',
    author: 'Jason Rekulak',
    publisher: 'Flatiron Books',
    description: 'Mallory Quinn is fresh out of rehab when she takes a job as a babysitter for Ted and Caroline Maxwell. She is to look after their five-year-old son, Teddy. Mallory immediately loves it. She has her own living space, goes out for nightly runs, and has the stability she craves. And she sincerely bonds with Teddy, a sweet, shy boy who is never without his sketchbook and pencil. His drawings are the usual fare: trees, rabbits, balloons. But one day, he draws something different: a man in a forest, dragging a woman\'s lifeless body.',
    isbn: '1250819350',
    genre: 'Thrillers',
    series: NULL,
    price: '13.00',
    quantity: '17',
    condition_new: true
  },
  {
    title: 'The Spy Coast',
    author: 'Tess Gerritsen',
    publisher: 'Thomas & Mercer',
    description: 'Former spy Maggie Bird came to the seaside village of Purity, Maine, eager to put the past behind her after a mission went tragically wrong. These days, she\'s living quietly on her chicken farm, still wary of blowback from the events that forced her early retirement.',
    isbn: '1662515138',
    genre: 'Thrillers',
    series: NULL,
    price: '15.00',
    quantity: '17',
    condition_new: true
  },
  {
    title: 'The Housemaid',
    author: 'Freida McFadden',
    publisher: 'Grand Central',
    description: 'Every day I clean the Winchesters\' beautiful house top to bottom. I collect their daughter from school. And I cook a delicious meal for the whole family before heading up to eat alone in my tiny room on the top floor.',
    isbn: '1538742578',
    genre: 'Thrillers',
    series: NULL,
    price: '10.00',
    quantity: '17',
    condition_new: true
  },
  {
    title: 'The Exchange: After The Firm',
    author: 'John Grisham',
    publisher: 'Doubleday',
    description: 'What became of Mitch and Abby McDeere after they exposed the crimes of Memphis law firm Bendini, Lambert & Locke and fled the country? The answer is in The Exchange, the riveting sequel to The Firm, the blockbuster thriller that launched the career of America\'s favorite storyteller. It is now fifteen years later, and Mitch and Abby are living in Manhattan, where Mitch is a partner at the largest law firm in the world.',
    isbn: '0385548958',
    genre: 'Thrillers',
    series: 'The Firm',
    price: '19.00',
    quantity: '17',
    condition_new: true
  },
  {
    title: 'One Last Kill',
    author: 'Robert Dugoni',
    publisher: 'Thomas & Mercer',
    description: 'Tracy Crosswhite is reopening the investigation into Seattle\'s Route 99 serial killer. After thirteen victims, he stopped hunting and the trail went cold, stirring public outrage. Now, nearly three decades after his first kill, Tracy is expected to finally bring closure to the victims\' families and redeem the Seattle PD\'s reputation. Even if it means working with her nemesis, Captain Johnny Nolasco.',
    isbn: '1662500211',
    genre: 'Thrillers',
    series: 'Tracy Crosswhite',
    price: '13.00',
    quantity: '17',
    condition_new: true
  },
  {
    title: 'The Paris Assignment',
    author: 'Rhys Bowen',
    publisher: 'Lake Union',
    description: 'Londoner Madeleine Grant is studying at the Sorbonne in Paris when she marries charismatic French journalist Giles Martin. As they raise their son, Olivier, they hold on to a tenuous promise for the future. Until the thunder of war sets off alarms in France.',
    isbn: '1662504233',
    genre: 'Historical',
    series: NULL,
    price: '13.00',
    quantity: '17',
    condition_new: true
  },
  {
    title: 'After Dunkirk',
    author: 'Lee Jackson',
    publisher: 'Severn River',
    description: 'Winston Churchill called it Britain\'s finest hour. The Royal Navy evacuated 330,000 soldiers from Dunkirk. But more than 200,000 were left behind. On the beaches, Jeremy Littlefield hides for his life.His path home will draw him through the iron will and the unbreakable heart of the French Resistance.',
    isbn: 'B08FPD4S8N',
    genre: 'Historical',
    series: 'After Dunkirk',
    price: '19.00',
    quantity: '17',
    condition_new: true
  },
  {
    title: 'When Heroes Flew',
    author: 'H. W. "Buzz" Bernard',
    publisher: 'Severn River',
    description: 'For B-24 bomber pilot Al Lycoming, the mission was history in the making.For Women\'s Airforce Service Pilot Vivian Wright, it was a chance to put her skills to the ultimate test...and share in the burden of combat. Dispatched to Benghazi on mysterious orders, Al Lycoming finds nearly 200 other B-24 bombers being assembled...and a top secret assignment that will catapult them all into seemingly impenetrable Nazi defenses. Their mission: a daring low-level attack on Hitler\'s extensive oil refineries.',
    isbn: 'B0849QV396',
    genre: 'Historical',
    series: 'When Heroes Flew',
    price: '18.00',
    quantity: '17',
    condition_new: true
  },
  {
    title: 'A Gentleman in Moscow',
    author: 'Amor Towles',
    publisher: 'Penguin Books',
    description: 'In 1922, Count Alexander Rostov is deemed an unrepentant aristocrat by a Bolshevik tribunal, and is sentenced to house arrest in the Metropol, a grand hotel across the street from the Kremlin. Rostov, an indomitable man of erudition and wit, has never worked a day in his life, and must now live in an attic room while some of the most tumultuous decades in Russian history are unfolding outside the hotel\'s doors. Unexpectedly, his reduced circumstances provide him entry into a much larger world of emotional discovery.',
    isbn: '0143110438',
    genre: 'Historical',
    series: NULL,
    price: '9.00',
    quantity: '17',
    condition_new: true
  },
  {
    title: 'The Last Protector',
    author: 'Simon Gervais',
    publisher: 'Thomas & Mercer',
    description: 'Former air force combat rescue officer Special Agent Clayton White now works for the Secret Service performing routine escort missions for politicians. These missions may not be quite as exciting as his time in the military, but Clayton\'s okay with that. It gives him more time to see his girlfriend, Veronica Hammond—an archaeologist who also happens to be the vice president elect\'s daughter.',
    isbn: 'B08LD2BRD9',
    genre: 'Historical',
    series: 'Clayton White',
    price: '10.00',
    quantity: '37',
    condition_new: true
  },
];

const seedBook = () => Book.bulkCreate(bookdata);

module.exports = seedBook;